spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:zXDSX4YyIUfm5OKZloxTQBV8kRIFzCLWFKjzEwwLkqYp7FD6@44ab58bc-9218-41b2-8ec4-e9d48b9bfd5c.asia-southeast1.firestore.goog:443/db-mediplus?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}