spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:r_Emcp5jfOQ1v2Les1ExDamzjxa6ZoPu7DVTMWZ-_aKVj247@365eaeb1-b29f-4927-9847-a351b5853fc0.asia-southeast1.firestore.goog:443/db-mediplus?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}